Отправляю на проверку выполненное задание «Камень судьбы»
htmlacademy-yii/824017-task-force-1 pull request #2
Opened 2021-02-22 09:19 UTC by mikeserov

2021-02-22 19:58 UTC, Shv-sergey70 requested changes

2021-02-22 19:58 UTC, Shv-sergey70 commented on composer.json
> +            "MyClasses\\": "src/"
Лучше корневой класс задавать по названию проекта или как-то еще, но не стоит просто `MyClass`

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	private int $customer_id;
В php обычно переменные именуются в camelCase. Это практический стандарт, не PSR конечно, но все же более распространено чем snake_case

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +		$this->cur_status = self::STATUS_NEW;
`cur_status` лучше не делать никаких сокращений в названиях переменных

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	];
В ключах стоит использовать созданные константы:
```
	private array $mapping = [
		self::STATUS_NEW => 'Новое',
		self::STATUS_CANCELED => 'Отменено', // и ниже в том же духе
		'executing' => 'В работе',
		'accomplished' => 'Выполнено',
		'failed' => 'Провалено',
		'to cancel' => 'Отменить',
		'to execute' => 'Откликнуться',
		'to accomplish' => 'Выполнено',
		'to fail' => 'Отказаться'
	];
```

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	];
Тут тоже стоит использовать созданные константы

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +		if ($is_able_to_change_cur_status = array_key_exists($this->cur_status, $this->status_changes)) {
Не, так делать не стоит. Никаких присваиваний в условиях, это bad practice

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +			case 'new': 										//нужно ли поставить в case константу вместо 'new', т.е. self::STATUS_NEW.
Да, обязательно. Теперь везде используем созданные константы

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +				}
Тут стоит использовать тернарный оператор

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +		return $available_action;  //не нарушается ли здесь правило критерия Б36?
Не нарушается, так как выше есть `default` блок

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	public function setStatus(string $new_status)
Стоит описать возвращаемое значение функцией

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +<?php
Предлагаю выполнять проект в строгом режиме, используя:
`declare(strict_types=1);`
https://www.brainbell.com/php/strict-type.html

Это позволит писать более качественный код

2021-02-22 19:58 UTC, Shv-sergey70 commented on test.php
> +assert($task->getMapping()['to fail'] == 'Отказаться', 'Корректное название действия на русском не получено');
сравнения по всему проекту должны быть строгими `===`

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	public function __construct(int $executant_id, int $customer_id) //нужно ли указывать 2-й параметр необязательным, т.е. ?int $customer_id=null
А в каких случаях он может быть необязательным?

2021-02-22 19:58 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	public function getMapping(): array
Вместо возвращения маппера, можно принимать параметром значение, описать внутри метода маппинг и возвращать нужное значение

2021-02-22 20:38 UTC, mikeserov commented on src/controllers/Task.php
> +	public function __construct(int $executant_id, int $customer_id) //нужно ли указывать 2-й параметр необязательным, т.е. ?int $customer_id=null
предположил ситуацию, когда заказчик создает задание, и в момент создания и размещения задания исполнителя еще нет, поэтому задумался.

2021-02-23 13:33 UTC, mikeserov commented on src/controllers/Task.php
> +	public function getMapping(): array
ты имеешь в виду реализовать возможность возвращения методом как значение ключа на английском, так и само значение элемента на русском?

2021-02-24 12:17 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	public function __construct(int $executant_id, int $customer_id) //нужно ли указывать 2-й параметр необязательным, т.е. ?int $customer_id=null
Тогда в целом справедливо, можно сделать nullable

2021-02-24 12:18 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +	public function getMapping(): array
Нет, ты в метод передаешь значение на английском, а он возвращает значение на русском

2021-02-24 12:19 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +		return null;
```
return $this->mapping[$actionOrStatusName] ?? null;
```

2021-02-24 12:19 UTC, Shv-sergey70 commented on test.php
> +declare(strict_types = 1);
По psr перед declare должен быть отступ

2021-02-24 12:19 UTC, merged

2021-02-24 16:12 UTC, mikeserov commented on src/controllers/Task.php
> +		return null;
То что нужно! Спасибо!)