Module2 task2
htmlacademy-yii/824017-task-force-1 pull request #5
Opened 2021-03-06 19:11 UTC by mikeserov

2021-03-09 17:18 UTC, Shv-sergey70 requested changes

2021-03-09 17:18 UTC, Shv-sergey70 commented on whole-task-class-test.php
> +
Это все убираем. Посмотри настройки редактора, наверняка есть возможность, чтобы он запрещал так делать

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +				!$isAvailableAction ?: $availableAction = $action;
Это сложно. Так лучше не писать

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/FailAction.php
> +	}
Нужно в функциях описать тип возвращаемых значений

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/FailAction.php
> +	public function getDisplayingName()
Между функциями стоит делать отступ в 1 пробел

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/FailAction.php
> +		return $currentUserId === $executantId ? true : false;
Результат сравнения - всегда булево значение, поэтому тернарный оператор тут лишний. Достаточно сделать так: `return $currentUserId === $executantId`

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/ExecuteAction.php
> +		return $currentUserRole === 'executant' && $currentUserId !== $customerId ? true : false;
`executant` - это должно быть сохранено константой класса

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/ExecuteAction.php
> +		return $currentUserRole === 'executant' && $currentUserId !== $customerId ? true : false;
`$currentUserId !== $customerId ? true : false;` - можно без тернарного оператора

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/ExecuteAction.php
> +	}
Тут то же что и в `FailAction`

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/CancelAction.php
> +}
Тут то же что и в `FailAction`

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/AccomplishAction.php
> +	}
Тут то же что и в `FailAction`

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/AbstractAction.php
> +	abstract public function canUserAct(int $customerId, int $executantId, int $currentUserId, ?string $currentUserRole);
Нужен хотя бы 1 отступ между свойствами и методами

2021-03-09 17:18 UTC, Shv-sergey70 commented on src/controllers/AccomplishAction.php
> +class AccomplishAction extends AbstractAction {
Все НЕ абстрактные классы можно помечать как `final` - это хорошая практика, которая позволяет ограничивать наследуемость

2021-03-09 17:57 UTC, mikeserov commented on src/controllers/Task.php
> +				!$isAvailableAction ?: $availableAction = $action;
заменю на if ?
```
if (isset($actions)) {
			foreach ($actions as $action) {
				if ($action->canUserAct($this->customerId, $this->executantId, $userId, $userRole)) {
					$availableAction = $action;
				}
			}
		}
```

2021-03-10 12:03 UTC, Shv-sergey70 requested changes
Нужно во всем проекте поправить отступы:
https://www.php-fig.org/psr/psr-12/#24-indenting

Табы не должны использоваться в качестве отступов. Только 4 пробела - это стандарт. Поменяй настройки своего редактора

2021-03-10 12:03 UTC, shershnevsergey commented on src/controllers/AbstractAction.php
> +	abstract public function canUserAct(int $customerId, int $executantId, int $currentUserId, ?string $currentUserRole);
Стоит описать возвращаемые типы функциями

2021-03-10 12:03 UTC, shershnevsergey commented on src/controllers/ExecuteAction.php
> +	const ROLE_EXECUTANT = 'executant';
Стоит ограничивать видимость константам явно, написав `private`.
Если не указать совсем - будет `public`

2021-03-10 12:03 UTC, shershnevsergey commented on src/controllers/Task.php
> +			}
А если написать так, получится та же логика ведь?
```
		$availableAction = null;

		switch ($this->currentStatus) {
			case self::STATUS_NEW:
				$actions = [new ExecuteAction, new CancelAction];
				break;
			case self::STATUS_EXECUTING:
				$actions = [new FailAction, new AccomplishAction];
				break;
            default:
                return null;
		}

        foreach ($actions as $action) {
            if ($action->canUserAct($this->customerId, $this->executantId, $userId, $userRole)) {
                $availableAction = $action;
            }
        }
        
		return $availableAction;
```

2021-03-10 12:03 UTC, Shv-sergey70 commented on src/controllers/Task.php
>  		return $availableAction;
Перед `return` и `if` стоит всегда оставлять пустую строку

2021-03-10 12:03 UTC, Shv-sergey70 commented on src/controllers/Task.php
> +				!$isAvailableAction ?: $availableAction = $action;
Написал в новых комментах способ

2021-03-10 13:13 UTC, mikeserov commented on src/controllers/Task.php
> +			}
Та же, да. И понимается проще. Спасибо!)

2021-03-10 16:57 UTC, merged