Исключительный тип
htmlacademy-yii/824017-task-force-1 pull request #6
Opened 2021-03-10 18:17 UTC by mikeserov

2021-03-11 11:49 UTC, Shv-sergey70 requested changes

2021-03-11 11:49 UTC, Shv-sergey70 commented on exception-test.php
> +use TaskForce\Controllers\Task;
Нужно переменовать папку `controllers` и написать ее первую букву в верхнем регистре, чтобы `namespace` совпадал

2021-03-11 11:49 UTC, Shv-sergey70 commented on exception-test.php
> +    error_log("Передан невалидный аргумент: " . $e->getMessage()); //у меня в логе появляются иероглифы вместо русских букв..
А где ты смотришь сообщение об ошибке и как ты запускаешь данный `exception-test.php`?

2021-03-11 13:16 UTC, mikeserov commented on exception-test.php
> +    error_log("Передан невалидный аргумент: " . $e->getMessage()); //у меня в логе появляются иероглифы вместо русских букв..
![1](https://user-images.githubusercontent.com/45338098/110792659-7c2d1780-8295-11eb-9c79-d106bc7b4b6f.jpg)

![2](https://user-images.githubusercontent.com/45338098/110792679-818a6200-8295-11eb-8bfb-e52cd549824b.jpg)

Запускаю OpenServer, открываю в браузере http://824017-task-force-1/exception-test.php, затем в меню OpenServera выбираю 'Просмотр логов'->вкладка 'PHP отладка'

2021-03-12 14:29 UTC, Shv-sergey70 commented on exception-test.php
> +    error_log("Передан невалидный аргумент: " . $e->getMessage()); //у меня в логе появляются иероглифы вместо русских букв..
Думаю это как-то опенсервер не так отображает логи. Что-то с кодировкой. Если просто в консоли запустить, то все тексты отображаются правильно

2021-03-12 14:29 UTC, merged

2021-03-12 14:58 UTC, mikeserov commented on exception-test.php
> +    error_log("Передан невалидный аргумент: " . $e->getMessage()); //у меня в логе появляются иероглифы вместо русских букв..
Попробую в консоли тогда, Спасибо!