Повелитель данных
htmlacademy-yii/824017-task-force-1 pull request #7
Opened 2021-03-12 15:50 UTC by mikeserov

2021-03-13 20:37 UTC, Shv-sergey70 requested changes

2021-03-13 20:37 UTC, Shv-sergey70 commented on converter-class-test.php
> +    $converter->convert();
Если класс нужен только чтобы вызвать 1 метод, то можно сразу так:
```
(new CsvToSqlConverter($table . '.csv'))->convert();
```

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +class CsvToSqlConverter
`final`

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        $this->dataBaseTable = explode('.', $csvName)[0] ?? null; //это же не является нарушением Б37?
Не является, потому что фактически ты и сделал проверку

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        $this->dataBaseTable = explode('.', $csvName)[0] ?? null; //это же не является нарушением Б37?
А если в `dataBaseTable` запишется null, как у тебя будет работать код? Ты же не сможешь в БД сохранить данные. Это не правильно сформированный класс будет. Лучше тут кинуть исключение

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +    private SplFileObject $sqlFileObject;
Это не стоит писать как приватные свойства. Они нужны только в рамках внутренних методов, их можно передавать параметрами

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        }
Эту проверку можно произвести в конструкторе, потому что нет смысла создавать этот класс, если файла нет

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +            throw new SourceFileException("Не удалось открыть CSV файл на чтение");
Чтобы этого не произошло, также в конструкторе можно проверить, что файл `is_writable`

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        $headers = $this->getHeaders();
Это не то чтобы `headers`, скорее обычные `columns`

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        $firstValues = $this->arrayToString($firstValues);
Тут можно так:
```
        $firstValues = $this->arrayToString(
            $this->csvFileObject->fgetcsv()
        );
```
Чтобы отказаться от перезаписи переменной `$firstValues`

2021-03-13 20:37 UTC, Shv-sergey70 commented on converter-class-test.php
> +<?php
А ты запускал этот тест-кейс? Он отрабатывает с ошибками ведь
![Снимок экрана 2021-03-13 в 23 34 20](https://user-images.githubusercontent.com/35741647/111043658-babd0080-8454-11eb-8f28-ca6cdf47cc7d.png)

2021-03-13 20:37 UTC, Shv-sergey70 commented on data/responses.sql
> +INSERT INTO responses (task_id, user_id, date_time, payment, comment)
Можно не хранить `.sql` файлы в репозитории, так как их всегда быстро можно создать из исходных `.csv` файлов скриптом, который ты создал

2021-03-13 20:37 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        $this->sqlName = 'data/' . $this->dataBaseTable . '.sql';
Давай `sql` файлы будет класть в подпапку внутри `data`. Например так `data/sql/`

2021-03-14 11:15 UTC, mikeserov commented on converter-class-test.php
> +<?php
сначала я не понял, а потом как понял.
может ты запускал с версией php до 7.4?
Кажется, это потомучто в определении свойств типы могут быть указаны при версии php 7.4 и выше

2021-03-14 12:03 UTC, mikeserov commented on src/Utils/CsvToSqlConverter.php
> +        $this->dataBaseTable = explode('.', $csvName)[0] ?? null; //это же не является нарушением Б37?
а оно же и так выбросится в виде TypeError, если в dataBaseTable запишется null, да?

2021-03-15 12:38 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +            $this->dataBaseTable = explode('.', $csvName)[0] ?? null;
Тут будет проблема, так как в `dataBaseTable` ты прописал тип `string`, а может ведь быть еще и null. Поэтому нужно так: `private ?string $dataBaseTable;`

2021-03-15 12:38 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        catch (RuntimeException $exception) {
Тут класс то не определен, это работать не будет. Может ты хотел так?
`\RuntimeException`

2021-03-15 13:18 UTC, Shv-sergey70 commented on src/Utils/CsvToSqlConverter.php
> +        $this->dataBaseTable = explode('.', $csvName)[0] ?? null;
Я тут осознал, что дальше если там null, ты кидаешь исключение. Поэтому можно не править тип свойства на `?string`. Но тогда нужно сделать иначе:
```
$dataBaseTable = explode('.', $csvName)[0] ?? null;

if (!$dataBaseTable) {
  throw new GivenArgumentException("dataBaseTable присвоено пустое значение")
}

$this->dataBaseTable = $dataBaseTable
```
Так будет невозможно записать null в свойство и все будет ок

2021-03-15 13:18 UTC, merged